// Tenants whose paid history was generated by the registration flow in this session. The background
// back-fill must leave them alone: both would insert the same months within milliseconds of each other
// (that produced duplicated history rows and doubled the "collected" figures).
const handled = new Set()
export const markHistoryHandled = (tenantId) => { if (tenantId) handled.add(tenantId) }
export const isHistoryHandled = (tenantId) => handled.has(tenantId)
